# Configuração da instância middleware
port: 9101
protocol: HTTP

# Identificação do serviço para registro no gateway
serviceType: isemail
instanceId: inst1

# Gateway
gatewayHost: localhost
gatewayHeartbeatPort: 9000
heartbeatIntervalMs: 3000
